# Generated by Django 4.2.30 on 2026-07-03 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('interval', models.CharField(db_index=True, max_length=8)),
                ('strategy_name', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trades', models.IntegerField()),
                ('win_rate', models.FloatField()),
                ('profit_factor', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('max_drawdown', models.FloatField()),
                ('total_return', models.FloatField(default=0.0)),
                ('summary', models.TextField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('interval', models.CharField(db_index=True, max_length=8)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('source', models.CharField(default='yfinance', max_length=64)),
                ('validation_flags', models.TextField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol', 'interval', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RAGDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=256)),
                ('document_type', models.CharField(default='document', max_length=64)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('metadata', models.TextField(blank=True, default=dict)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='TrainingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=64)),
                ('model_family', models.CharField(default='regression', max_length=32)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('interval', models.CharField(db_index=True, max_length=8)),
                ('target', models.CharField(default='close', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metrics', models.TextField(default=dict)),
                ('hyperparameters', models.TextField(blank=True, default=dict)),
                ('artifact_path', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'symbol', 'interval'], name='myapp_train_model_n_7a6cd5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RAGDocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding_model', models.CharField(default='hashing-vectorizer', max_length=128)),
                ('vector_store_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.TextField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='myapp.ragdocument')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('interval', models.CharField(db_index=True, max_length=8)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('signal', models.CharField(max_length=16)),
                ('confidence', models.FloatField()),
                ('buy_probability', models.FloatField()),
                ('sell_probability', models.FloatField()),
                ('hold_probability', models.FloatField()),
                ('current_price', models.FloatField()),
                ('horizon_prices', models.TextField(default=dict)),
                ('model_outputs', models.TextField(default=dict)),
                ('feature_snapshot', models.TextField(default=dict)),
                ('explanation', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['symbol', 'interval', '-generated_at'], name='myapp_predi_symbol_6cdb77_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=32)),
                ('source', models.CharField(max_length=128)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=512)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=1024)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('bullish_score', models.FloatField(blank=True, null=True)),
                ('bearish_score', models.FloatField(blank=True, null=True)),
                ('impact_score', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.TextField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['symbol', '-published_at'], name='myapp_newsa_symbol_0e492f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='newsarticle',
            constraint=models.UniqueConstraint(fields=('source', 'url'), name='unique_news_source_url'),
        ),
        migrations.AddIndex(
            model_name='historicalmarketdata',
            index=models.Index(fields=['symbol', 'interval', 'timestamp'], name='myapp_histo_symbol_2ad97b_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicalmarketdata',
            constraint=models.UniqueConstraint(fields=('symbol', 'interval', 'timestamp'), name='unique_market_candle'),
        ),
        migrations.AddIndex(
            model_name='backtestresult',
            index=models.Index(fields=['symbol', 'interval', 'strategy_name'], name='myapp_backt_symbol_0a0a8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'symbol'), name='unique_user_symbol_watchlist'),
        ),
        migrations.AddConstraint(
            model_name='ragdocumentembedding',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_rag_document_chunk'),
        ),
    ]
