from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import Any

import numpy as np
import pandas as pd


@dataclass
class BacktestSummary:
    symbol: str
    interval: str
    start_date: date
    end_date: date
    trades: int
    win_rate: float
    profit_factor: float
    sharpe_ratio: float
    max_drawdown: float
    summary: dict[str, Any]


def generate_signals(df: pd.DataFrame) -> pd.Series:
    short_ema = df["Close"].ewm(span=12, adjust=False).mean()
    long_ema = df["Close"].ewm(span=26, adjust=False).mean()
    crossover = short_ema > long_ema
    return crossover.astype(int).diff().fillna(0)


def run_backtest(
    df: pd.DataFrame,
    stop_loss_pct: float = 0.02,
    take_profit_pct: float = 0.04,
    starting_balance: float = 10000.0,
) -> BacktestSummary:
    df = df.copy().reset_index(drop=True)
    signals = generate_signals(df)

    trades = []
    balance = starting_balance
    entry_price = None
    entry_index = None

    for idx in range(1, len(df)):
        if signals.iloc[idx] > 0 and entry_price is None:
            entry_price = df.loc[idx, "Close"]
            entry_index = idx
        elif entry_price is not None:
            current_price = df.loc[idx, "Close"]
            change = (current_price / entry_price) - 1
            if change <= -stop_loss_pct or change >= take_profit_pct or signals.iloc[idx] < 0:
                trades.append(change)
                entry_price = None
                entry_index = None

    if not trades:
        return BacktestSummary(
            symbol="",
            interval="",
            start_date=df.loc[0, "Date"].date() if "Date" in df.columns else date.today(),
            end_date=df.loc[len(df) - 1, "Date"].date() if "Date" in df.columns else date.today(),
            trades=0,
            win_rate=0.0,
            profit_factor=0.0,
            sharpe_ratio=0.0,
            max_drawdown=0.0,
            summary={"reason": "No trades generated by the strategy."},
        )

    returns = np.array(trades)
    wins = float((returns > 0).sum())
    losses = float((returns <= 0).sum())
    win_rate = wins / len(returns)
    gross_profit = returns[returns > 0].sum() if returns[returns > 0].size else 0.0
    gross_loss = abs(returns[returns <= 0].sum()) if returns[returns <= 0].size else 0.0
    profit_factor = float(gross_profit / max(gross_loss, 1e-8))
    mean_return = returns.mean()
    std_return = returns.std(ddof=1) if len(returns) > 1 else 0.0
    sharpe_ratio = float(mean_return / std_return) if std_return > 0 else 0.0

    drawdowns = np.maximum.accumulate(1 + returns) - (1 + returns)
    max_drawdown = float(np.max(drawdowns)) if drawdowns.size else 0.0

    return BacktestSummary(
        symbol="",
        interval="",
        start_date=df.loc[0, "Date"].date() if "Date" in df.columns else date.today(),
        end_date=df.loc[len(df) - 1, "Date"].date() if "Date" in df.columns else date.today(),
        trades=len(returns),
        win_rate=float(win_rate),
        profit_factor=float(profit_factor),
        sharpe_ratio=float(sharpe_ratio),
        max_drawdown=float(max_drawdown),
        summary={
            "total_return": float(np.sum(returns)),
            "average_return": float(mean_return),
            "winning_trades": int(wins),
            "losing_trades": int(losses),
        },
    )
